site_name: Using SPDX
site_description: Information on how to use the System Package Data Exchange specification
site_author: The Linux Foundation and its Contributors.
site_url: https://spdx.github.io/using/  # set to the "root" of the site, to be combined with canonical_version
repo_url: https://github.com/spdx/using/
edit_uri: "edit/main/docs"  # set to an empty string to disable edit links;
copyright: Using SPDX Copyright Â© 2024, The Linux Foundation and its Contributors.
use_directory_urls: true
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo-white.svg
  features:
    - content.action.edit
plugins:
- search
- social:
    cards_layout_options:
      logo: docs/assets/images/ourlogo.png
- tags
markdown_extensions:
- admonition
- abbr
- def_list
- pymdownx.details
- pymdownx.superfences
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
nav:
- "Home": index.md
- "Getting started": getting-started.md
- "Cross referencing": cross-ref.md
- "Including security information in a SPDX document": including-security-info-in-spdx.md
- "Using SPDX License List short identifiers in source files": using-spdx-short-id-in-source-files.md
- "Using SPDX to comply with norms, standards and regulation": using-spdx-to-comply-with-norms.md
- "Differences from previous editions": diffs-from-previous-editions.md
- "Browse by tags": tags.md
